import type { Metadata } from 'next';
import { inter } from './fonts';

import NavBar from '@/components/layout/NavBar';
import FooterWithCta from '@/components/layout/FooterWithCta';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <NavBar />
        <main className="mb-[80px] md:mb-[130px] lg:mb-[160px]">
          {children}
        </main>
        <FooterWithCta />
      </body>
    </html>
  );
}
